# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
config.ssh.insert_key = false
config.vm.provider :virtualbox do |vb|
vb.customize ["modifyvm", :id, "--memory", "2048"]
end



# Application server 1.
config.vm.define "assign" do |app|
app.vm.hostname = "farrukhubuntu"
app.vm.box = "ubuntu/focal64"
app.vm.network :private_network, ip: "192.168.88.8"
end

config.vm.provision "ansible_local" do |ansible|
ansible.playbook = "provisioning/playbook.yml"
end


end
